In [1]:
import numpy as np

In [9]:
x = np.arange(1,10,3)
print(x)
y = np.linspace(1, 10, 5)  
print(y)


[1 4 7]
[ 1.    3.25  5.5   7.75 10.  ]


In [10]:
cords = np.meshgrid(x, y)
for i in range(len(cords[0])):
    for j in range(len(cords[0][i])):
        print(f"({cords[0][i][j]}, {cords[1][i][j]})")

(1, 1.0)
(4, 1.0)
(7, 1.0)
(1, 3.25)
(4, 3.25)
(7, 3.25)
(1, 5.5)
(4, 5.5)
(7, 5.5)
(1, 7.75)
(4, 7.75)
(7, 7.75)
(1, 10.0)
(4, 10.0)
(7, 10.0)


In [19]:
print(cords[0].shape, cords[1].ndim, cords[1].size)

(5, 3) 2 15


In [147]:
mat = np.array([[1, 2, 3, 4], [4, 5, 6, 7],[9, 10, 11, 12],[13, 14, 15, 16]])
print(mat[0:2,])  # Row range select
print(mat[:,0:2]) # Column range select

[[1 2 3 4]
 [4 5 6 7]]
[[ 1  2]
 [ 4  5]
 [ 9 10]
 [13 14]]


In [148]:
mat[:,[0, 2]]  # Select cols 0 and 2


array([[ 1,  3],
       [ 4,  6],
       [ 9, 11],
       [13, 15]])

# Create

In [54]:
np.zeros((2, 3)) # Create a 2x3 matrix of zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [53]:
np.ones((2, 3, 5)) 

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [58]:
np.full((2, 5), 5) # Create a 2x3 matrix filled with 5

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [52]:
np.random.seed(412)
x = np.random.randint(1, 10, size=(4, 4))
x

array([[3, 6, 3, 2],
       [2, 2, 2, 8],
       [6, 7, 5, 5],
       [4, 1, 7, 4]])

In [59]:
np.random.random_sample((2, 3)) # Create a 2x3 matrix with random floats between 0 and 1

array([[0.41050348, 0.79019146, 0.74769137],
       [0.41515395, 0.49400242, 0.91715966]])

In [60]:
np.identity(3) # Create a 3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Math

In [78]:
np.sin(x) # Calculate sine of pi/2

array([[ 0.14112001, -0.2794155 ,  0.14112001,  0.90929743],
       [ 0.90929743,  0.90929743,  0.90929743,  0.98935825],
       [-0.2794155 ,  0.6569866 , -0.95892427, -0.95892427],
       [-0.7568025 ,  0.84147098,  0.6569866 , -0.7568025 ]])

# Linear algebra

In [84]:
y = np.random.randint(1, 10, size=(4,1))
np.matmul(x, y) # Matrix multiplication

array([[ 78],
       [104],
       [142],
       [ 97]])

In [85]:
np.linalg.inv(x) # Inverse of a matrix

array([[-6.66666667e-01, -1.71497585e-01,  6.37681159e-01,
        -1.20772947e-01],
       [ 3.33333333e-01,  3.14009662e-02, -1.44927536e-01,
        -4.83091787e-02],
       [ 3.33333333e-01,  2.41545894e-03, -3.18840580e-01,
         2.27053140e-01],
       [-2.35989435e-17,  1.59420290e-01, -4.34782609e-02,
        -1.44927536e-02]])

In [86]:
np.linalg.det(x) # Determinant of a matrix

-413.99999999999994

In [ ]:
np.linalg.eig(x) # Eigen values of a matrix

(array([16.90782597+0.j        , -1.05494872+0.j        ,
        -0.92643863+4.72779404j, -0.92643863-4.72779404j]),
 array([[-0.39031028+0.j        , -0.82355032+0.j        ,
         -0.24774447-0.40093653j, -0.24774447+0.40093653j],
        [-0.41094191+0.j        ,  0.34485432+0.j        ,
          0.6272189 +0.j        ,  0.6272189 -0.j        ],
        [-0.6505234 +0.j        ,  0.44877252+0.j        ,
         -0.22400297-0.21553634j, -0.22400297+0.21553634j],
        [-0.50557289+0.j        , -0.03799458+0.j        ,
         -0.11150284+0.52478844j, -0.11150284-0.52478844j]]))

# Statistics


In [89]:
d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Mean ",np.mean(d)) # Mean of all elements
print("Mean column", np.mean(d, axis=0)) # Mean of each column
print("Mean row", np.mean(d, axis=1)) # Mean of each row

Mean  5.0
Mean column [4. 5. 6.]
Mean row [2. 5. 8.]


# General utility

In [92]:
n = np.array([[1, 2, 3, 4], [ 6, 7, 8, 9]])
n.reshape(4,2) # Reshape to 2 rows and 4 columns

array([[1, 2],
       [3, 4],
       [6, 7],
       [8, 9]])

In [ ]:
v1 = np.array([1, 2, 3])
np.vstack([v1]*5) # Stack vectors vertically

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [96]:
v1 = np.zeros((3, 3))
v2 = np.ones((3, 3))
v3 = np.hstack([v1,v2])

# Misc

In [98]:
v3 > .5

array([[False, False, False,  True,  True,  True],
       [False, False, False,  True,  True,  True],
       [False, False, False,  True,  True,  True]])

In [146]:
r = np.random.randint(1, 10, size=(3, 3))
r > 5
r[r > 5]   # Set all elements greater than 5 to 0

array([8, 9, 9, 9, 7])